version: '3.7'

services:
  app:
    build: .
    container_name: my-food-payment-app
    depends_on:
      - db
    image: my-food-payment-app:latest
    ports:
      - 8000:8000
    volumes:
      - source: .
        target: /app
        type: bind

  db:
    container_name: my-food-payment-db
    image: postgres:15.4
    env_file: .env
    ports:
      - 5432:5432
    network_mode: "host" # remove if running the app container
